import { useEffect, useMemo, useState } from 'react'
import { Activity, Filter, RefreshCw } from 'lucide-react'
import { apiGet, withQuery } from '../api/client'
import { Button, Card, EmptyState, ErrorState, Input, LoadingState, PageHeader, Pagination } from '../components/ui'
import { formatDateTime, humanize } from '../utils/format'

const pageSize = 15
export default function AuditLogsPage() {
  const [rows, setRows] = useState([]); const [filters, setFilters] = useState({ action: '', entity_type: '' }); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load() { setLoading(true); setError(''); try { setRows(await apiGet(withQuery('/admin/audit-logs', { ...filters, limit: 500 }))); setPage(1) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const visible = useMemo(() => rows.slice((page - 1) * pageSize, page * pageSize), [rows, page])
  return <div className="space-y-6"><PageHeader eyebrow="Accountability" title="Audit logs" description="Trace who changed registrations, events, attendance, fixtures, certificates and admin accounts." actions={<Button variant="secondary" icon={RefreshCw} onClick={load}>Refresh</Button>} /><Card className="p-4"><form className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]" onSubmit={(e) => { e.preventDefault(); load() }}><Input value={filters.action} onChange={(e) => setFilters((v) => ({ ...v, action: e.target.value }))} placeholder="Action, e.g. CREATE_EVENT" aria-label="Audit action" /><Input value={filters.entity_type} onChange={(e) => setFilters((v) => ({ ...v, entity_type: e.target.value }))} placeholder="Entity type, e.g. REGISTRATION" aria-label="Entity type" /><Button type="submit" icon={Filter}>Filter</Button></form></Card>
    {loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : rows.length === 0 ? <Card><EmptyState icon={Activity} title="No audit records found" description="Admin activity will appear here as operations are performed." /></Card> : <div className="table-shell"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{['Time','Actor','Action','Entity','Reason','Details'].map((h) => <th key={h} className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map((row) => <tr key={row.id} className="align-top hover:bg-slate-50"><td className="table-cell whitespace-nowrap">{formatDateTime(row.created_at)}</td><td className="table-cell"><p className="font-semibold">{humanize(row.actor_type)}</p><p className="mt-1 max-w-36 truncate text-xs text-slate-400">{row.actor_id || 'System'}</p></td><td className="table-cell font-bold text-brand-800">{humanize(row.action)}</td><td className="table-cell"><p className="font-semibold">{humanize(row.entity_type)}</p><p className="mt-1 max-w-36 truncate text-xs text-slate-400">{row.entity_id || '—'}</p></td><td className="table-cell max-w-72">{row.reason || '—'}</td><td className="table-cell"><details><summary className="cursor-pointer text-xs font-bold text-brand-700">View JSON</summary><pre className="mt-2 max-w-md overflow-auto rounded-lg bg-slate-950 p-3 text-[11px] text-slate-100">{JSON.stringify(row.details, null, 2)}</pre></details></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={pageSize} total={rows.length} onPageChange={setPage} /></div>}
  </div>
}
