import { useEffect, useState } from 'react'
import { CheckCircle2, FileBadge, FileUp, PlusCircle, RefreshCw, Send, UsersRound } from 'lucide-react'
import { apiGet, apiPost, withQuery } from '../api/client'
import { StatusBadge } from '../components/StatusBadge'
import { Button, Card, EmptyState, ErrorState, Input, LoadingState, PageHeader, Select, Textarea } from '../components/ui'
import { useToast } from '../context/ToastContext'
import { formatDateTime } from '../utils/format'

const defaultMapping = JSON.stringify({ page_width: 842, page_height: 595, name_x: 421, name_y: 310, name_font_size: 26, details_x: 421, details_y: 265, details_font_size: 13, number_x: 70, number_y: 40, number_font_size: 9, text_color: '#000000' }, null, 2)

export default function CertificatesPage() {
  const { notify } = useToast()
  const [events,setEvents]=useState([]); const [templates,setTemplates]=useState([]); const [eligible,setEligible]=useState([]); const [eventStudents,setEventStudents]=useState([]); const [corrections,setCorrections]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const [eventId,setEventId]=useState(''); const [templateId,setTemplateId]=useState(''); const [publishImmediately,setPublishImmediately]=useState(false); const [saving,setSaving]=useState(''); const [search,setSearch]=useState('')
  const [templateForm,setTemplateForm]=useState({name:'',event_config_id:'',field_mapping_json:defaultMapping,file:null})
  async function load(){setLoading(true);setError('');try{const [e,t,c]=await Promise.all([apiGet('/admin/events'),apiGet('/admin/certificates/templates'),apiGet(withQuery('/admin/certificates/correction-requests',{status:'OPEN'}))]);setEvents(e);setTemplates(t);setCorrections(c)}catch(err){setError(err.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  async function loadEligibility(id=eventId){if(!id){notify('Select an event first.','warning');return}setSaving('eligible');try{const [ok,all]=await Promise.all([apiGet(`/admin/certificates/eligible/${id}`),apiGet(`/admin/certificates/students/${id}`)]);setEligible(ok);setEventStudents(all)}catch(err){notify(err.message,'error')}finally{setSaving('')}}
  async function uploadTemplate(e){e.preventDefault();if(!templateForm.name.trim()||!templateForm.file){notify('Enter a template name and select a file.','warning');return}try{JSON.parse(templateForm.field_mapping_json)}catch{notify('Field mapping must be valid JSON.','warning');return}const body=new FormData();body.append('name',templateForm.name.trim());if(templateForm.event_config_id)body.append('event_config_id',templateForm.event_config_id);body.append('field_mapping_json',templateForm.field_mapping_json);body.append('file',templateForm.file);setSaving('upload');try{await apiPost('/admin/certificates/templates',body);notify('Certificate template uploaded.','success');setTemplateForm({name:'',event_config_id:'',field_mapping_json:defaultMapping,file:null});e.target.reset();await load()}catch(err){notify(err.message,'error')}finally{setSaving('')}}
  async function override(student,eligibleValue){const reason=window.prompt(eligibleValue?'Reason for manually adding this missed participant to certificate eligibility:':'Reason for removing the manual eligibility override:');if(!reason?.trim())return;setSaving(`override-${student.student_id}`);try{const result=await apiPost(`/admin/certificates/eligibility/${student.student_id}/override`,{eligible:eligibleValue,reason:reason.trim()});notify(result.message,'success');await loadEligibility()}catch(err){notify(err.message,'error')}finally{setSaving('')}}
  async function generate(){if(!eventId||!templateId){notify('Select both an event and a template.','warning');return}setSaving('generate');try{const r=await apiPost('/admin/certificates/generate',{event_config_id:eventId,template_id:templateId,publish_immediately:publishImmediately});notify(`Generated ${r.generated}; skipped ${r.skipped_existing}.`,'success');await loadEligibility()}catch(err){notify(err.message,'error')}finally{setSaving('')}}
  async function publish(){if(!eventId){notify('Select an event first.','warning');return}setSaving('publish');try{const r=await apiPost(`/admin/certificates/publish/${eventId}`,{});notify(r.message,'success')}catch(err){notify(err.message,'error')}finally{setSaving('')}}
  async function resolve(request,action){const note=window.prompt(action==='APPROVE_REISSUE'?'Enter the reissue note:':'Enter the rejection note:');if(!note?.trim())return;try{const r=await apiPost(`/admin/certificates/correction-requests/${request.id}/resolve`,{action,admin_note:note.trim()});notify(r.message,'success');await load()}catch(err){notify(err.message,'error')}}
  const filtered=eventStudents.filter(s=>`${s.name} ${s.usn} ${s.college} ${s.registration_code}`.toLowerCase().includes(search.toLowerCase()))

  return <div className="space-y-6"><PageHeader eyebrow="Certificate operations" title="Participation certificates" description="Attendance is the default eligibility rule. Certificate admins can explicitly add a missed participant with a recorded reason." actions={<Button variant="secondary" icon={RefreshCw} onClick={load}>Refresh</Button>} />
  {loading?<LoadingState label="Loading certificate module"/>:error?<ErrorState message={error} onRetry={load}/>:<>
    <div className="grid gap-6 xl:grid-cols-[.78fr_1.22fr]">
      <Card className="p-5"><h2 className="section-title">Upload certificate template</h2><p className="section-copy">PDF, JPG or PNG approved by BNMIT ODYSSEY organisers.</p><form onSubmit={uploadTemplate} className="mt-5 space-y-4"><Input label="Template name" value={templateForm.name} onChange={e=>setTemplateForm(v=>({...v,name:e.target.value}))} placeholder="Participation certificate 2026"/><Select label="Assign to event" value={templateForm.event_config_id} onChange={e=>setTemplateForm(v=>({...v,event_config_id:e.target.value}))}><option value="">General template</option>{events.map(event=><option key={event.id} value={event.id}>{event.sport_name} · {event.category}</option>)}</Select><div><label className="field-label" htmlFor="certificate-template">Template file</label><input id="certificate-template" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setTemplateForm(v=>({...v,file:e.target.files?.[0]||null}))} className="field-control file:mr-3 file:rounded-lg file:border-0 file:bg-brand-50 file:px-3 file:py-1.5 file:text-xs file:font-bold file:text-brand-800"/></div><Textarea label="Field mapping JSON" value={templateForm.field_mapping_json} onChange={e=>setTemplateForm(v=>({...v,field_mapping_json:e.target.value}))} className="[&_textarea]:min-h-64 [&_textarea]:font-mono [&_textarea]:text-xs"/><Button type="submit" className="w-full" icon={FileUp} loading={saving==='upload'}>Upload template</Button></form></Card>
      <div className="space-y-5"><Card className="p-5"><h2 className="section-title">Generate certificate batch</h2><p className="section-copy">Select an event, review eligibility, generate and then publish. Published PDFs are emailed to students and PEDs.</p><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Event and category" value={eventId} onChange={e=>{setEventId(e.target.value);setEligible([]);setEventStudents([])}}><option value="">Select event</option>{events.map(event=><option key={event.id} value={event.id}>{event.event_type} · {event.sport_name} · {event.category}</option>)}</Select><Select label="Template" value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Select template</option>{templates.filter(t=>!t.event_config_id||t.event_config_id===eventId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select></div><label className="mt-4 flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" checked={publishImmediately} onChange={e=>setPublishImmediately(e.target.checked)} className="h-4 w-4 rounded text-brand-700"/>Publish immediately after generation</label><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" icon={UsersRound} loading={saving==='eligible'} onClick={()=>loadEligibility()}>Review eligibility</Button><Button icon={FileBadge} loading={saving==='generate'} onClick={generate}>Generate certificates</Button><Button variant="accent" icon={Send} loading={saving==='publish'} onClick={publish}>Publish drafts</Button></div></Card>
        <Card className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="section-title">Eligible students</h2><p className="section-copy">Present students plus approved manual overrides.</p></div>{eligible.length===0?<EmptyState icon={UsersRound} title="Eligibility not loaded" description="Select an event and click Review eligibility."/>:<div className="max-h-96 divide-y divide-slate-100 overflow-auto">{eligible.map(s=><div key={s.student_id} className="flex items-center justify-between gap-3 px-5 py-4"><div><p className="font-bold text-slate-950">{s.name}</p><p className="mt-1 text-xs text-slate-500">{s.usn} · {s.college} · {s.registration_code}</p></div><StatusBadge status="PRESENT"/></div>)}</div>}</Card>
      </div>
    </div>

    <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-200 px-5 py-4 md:flex-row md:items-end md:justify-between"><div><h2 className="section-title">Missed participant override</h2><p className="section-copy">Use only when an otherwise valid participant was missed during attendance. Every override stores the admin, time and reason.</p></div><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student, USN or college" className="w-full md:w-80"/></div>{eventStudents.length===0?<EmptyState icon={PlusCircle} title="Load an event roster" description="Review eligibility first to see all approved-registration students."/>:<div className="divide-y divide-slate-100">{filtered.map(s=><div key={s.student_id} className="grid gap-3 p-5 md:grid-cols-[1fr_auto] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-slate-950">{s.name}</p><StatusBadge status={s.attendance_status}/>{s.certificate_override?<span className="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-bold text-violet-700">MANUAL OVERRIDE</span>:null}</div><p className="mt-1 text-xs text-slate-500">{s.usn} · {s.college} · {s.registration_code}</p>{s.certificate_override_reason?<p className="mt-1 text-xs text-violet-700">Reason: {s.certificate_override_reason}</p>:null}</div>{s.attendance_status==='PRESENT'?<span className="text-xs font-semibold text-emerald-700">Automatically eligible</span>:s.certificate_override?<Button size="sm" variant="secondary" loading={saving===`override-${s.student_id}`} onClick={()=>override(s,false)}>Remove override</Button>:<Button size="sm" icon={PlusCircle} loading={saving===`override-${s.student_id}`} onClick={()=>override(s,true)}>Add missed student</Button>}</div>)}</div>}</Card>

    <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="section-title">Open correction requests</h2><p className="section-copy">Approve reissue only after verifying the requested spelling or data correction.</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">{corrections.length} open</span></div>{corrections.length===0?<EmptyState icon={CheckCircle2} title="No open corrections" description="All certificate correction requests are resolved."/>:<div className="divide-y divide-slate-100">{corrections.map(r=><div key={r.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2"><p className="font-bold text-slate-950">Request {r.id.slice(0,8)}</p><StatusBadge status={r.status}/></div><p className="mt-2 text-sm text-slate-600">{r.reason}</p><p className="mt-2 text-xs text-slate-400">Created {formatDateTime(r.created_at)}</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>resolve(r,'REJECT')}>Reject</Button><Button size="sm" onClick={()=>resolve(r,'APPROVE_REISSUE')}>Approve reissue</Button></div></div>)}</div>}</Card>
  </>}</div>
}
