import { useEffect, useState } from 'react'
import { ExternalLink, FileUp, RefreshCw, Send } from 'lucide-react'
import { apiGet, apiPost } from '../api/client'
import { StatusBadge } from '../components/StatusBadge'
import { Button, Card, EmptyState, ErrorState, Input, LoadingState, PageHeader, Select, Textarea } from '../components/ui'
import { useToast } from '../context/ToastContext'
import { formatDateTime } from '../utils/format'

export default function FixturesPage() {
  const { notify } = useToast()
  const [events, setEvents] = useState([]); const [published, setPublished] = useState([]); const [recent, setRecent] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ title: '', event_config_id: '', note: '', visibility: 'RELEVANT_PEDS', supersedes_id: '', file: null })
  async function load() { setLoading(true); setError(''); try { const [eventRows, fixtureRows] = await Promise.all([apiGet('/admin/events'), apiGet('/public/fixtures')]); setEvents(eventRows); setPublished(fixtureRows) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  function update(key, value) { setForm((current) => ({ ...current, [key]: value })) }
  async function upload(e) {
    e.preventDefault(); if (!form.title.trim() || !form.file) { notify('Add a title and choose a PDF, JPG or PNG file.', 'warning'); return }
    const body = new FormData(); body.append('title', form.title.trim()); if (form.event_config_id) body.append('event_config_id', form.event_config_id); if (form.note) body.append('note', form.note); body.append('visibility', form.visibility); if (form.supersedes_id) body.append('supersedes_id', form.supersedes_id); body.append('file', form.file)
    setSaving(true)
    try { const result = await apiPost('/admin/fixtures', body); setRecent((rows) => [{ ...result, title: form.title, event_config_id: form.event_config_id }, ...rows]); notify('Fixture uploaded as a draft. Publish it when ready.', 'success'); setForm({ title: '', event_config_id: '', note: '', visibility: 'RELEVANT_PEDS', supersedes_id: '', file: null }); e.target.reset() } catch (err) { notify(err.message, 'error') } finally { setSaving(false) }
  }
  async function publish(id) { try { const result = await apiPost(`/admin/fixtures/${id}/publish`, {}); notify(result.message, 'success'); setRecent((rows) => rows.map((row) => row.id === id ? { ...row, status: 'PUBLISHED' } : row)); await load() } catch (err) { notify(err.message, 'error') } }

  return <div className="space-y-6"><PageHeader eyebrow="Fixture operations" title="Fixtures and draws" description="Upload event/category-wise fixture copies, publish them to PEDs, and clearly replace outdated versions." actions={<Button variant="secondary" icon={RefreshCw} onClick={load}>Refresh</Button>} />
    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]">
      <Card className="p-5"><h2 className="section-title">Upload fixture copy</h2><p className="section-copy">Files remain draft until you explicitly publish them.</p><form className="mt-5 space-y-4" onSubmit={upload}><Input label="Fixture title" value={form.title} onChange={(e) => update('title', e.target.value)} placeholder="Volleyball preliminary draw" required /><Select label="Event and category" value={form.event_config_id} onChange={(e) => update('event_config_id', e.target.value)}><option value="">General fixture</option>{events.map((event) => <option key={event.id} value={event.id}>{event.sport_name} · {event.category}</option>)}</Select><Select label="Visibility" value={form.visibility} onChange={(e) => update('visibility', e.target.value)}><option value="RELEVANT_PEDS">Relevant PEDs</option><option value="ALL_PEDS">All registered PEDs</option><option value="PUBLIC">Public website</option></Select><Input label="Supersedes fixture ID" value={form.supersedes_id} onChange={(e) => update('supersedes_id', e.target.value)} placeholder="Optional previous fixture ID" hint="Use this only when uploading a revised fixture." /><Textarea label="Publication note" value={form.note} onChange={(e) => update('note', e.target.value)} placeholder="Reporting change, court allocation or version note" /><div><label className="field-label" htmlFor="fixture-file">Fixture file</label><input id="fixture-file" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(e) => update('file', e.target.files?.[0] || null)} className="field-control file:mr-3 file:rounded-lg file:border-0 file:bg-brand-50 file:px-3 file:py-1.5 file:text-xs file:font-bold file:text-brand-800" /><p className="helper-text">Accepted: PDF, JPG or PNG. Maximum 15 MB.</p></div><Button type="submit" className="w-full" icon={FileUp} loading={saving}>Upload draft fixture</Button></form></Card>
      <div className="space-y-5">
        {recent.length ? <Card className="p-5"><h2 className="section-title">Recently uploaded in this session</h2><p className="section-copy">Publish a draft to trigger PED emails and make the file available.</p><div className="mt-4 space-y-3">{recent.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4"><div><p className="font-bold text-slate-950">{item.title}</p><p className="mt-1 text-xs text-slate-500">Version {item.version} · {item.id}</p></div><div className="flex items-center gap-2"><StatusBadge status={item.status} />{item.status !== 'PUBLISHED' ? <Button size="sm" icon={Send} onClick={() => publish(item.id)}>Publish</Button> : null}</div></div>)}</div></Card> : null}
        <Card className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="section-title">Publicly published fixtures</h2><p className="section-copy">The backend currently exposes public fixtures here. PED-only publications remain available through PED endpoints.</p></div>{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : published.length === 0 ? <EmptyState title="No public fixtures published" description="Upload a fixture with Public visibility and publish it to show it here." /> : <div className="divide-y divide-slate-100">{published.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-bold text-slate-950">{item.title}</p><p className="mt-1 text-xs text-slate-500">Version {item.version} · {formatDateTime(item.published_at)}</p>{item.note ? <p className="mt-2 text-sm text-slate-600">{item.note}</p> : null}</div><a href={item.download_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50">Open file <ExternalLink className="h-4 w-4" /></a></div>)}</div>}</Card>
      </div>
    </div>
  </div>
}
