import { useEffect, useState } from 'react'
import { ExternalLink, Radio, RefreshCw, Save } from 'lucide-react'
import { apiGet, apiPost } from '../api/client'
import { StatusBadge } from '../components/StatusBadge'
import { Button, Card, EmptyState, ErrorState, Input, LoadingState, PageHeader, Select, Textarea } from '../components/ui'
import { useToast } from '../context/ToastContext'
import { fromDateTimeLocal, toDateTimeLocal } from '../utils/format'

export default function LiveStreamsPage() {
  const { notify } = useToast(); const [events, setEvents] = useState([]); const [streams, setStreams] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ event_config_id: '', title: '', youtube_url: '', visibility: 'PUBLIC', status: 'SCHEDULED', offline_message: '', scheduled_at: '' })
  async function load() { setLoading(true); setError(''); try { const [eventRows, streamRows] = await Promise.all([apiGet('/admin/events'), apiGet('/public/live-streams')]); setEvents(eventRows); setStreams(streamRows) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  function update(key, value) { setForm((current) => ({ ...current, [key]: value })) }
  function edit(stream) { setForm({ event_config_id: stream.event_config_id || '', title: stream.title, youtube_url: stream.youtube_url, visibility: 'PUBLIC', status: stream.status, offline_message: stream.offline_message || '', scheduled_at: toDateTimeLocal(stream.scheduled_at) }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  async function save(e) { e.preventDefault(); if (!form.title.trim() || !/^https?:\/\//.test(form.youtube_url)) { notify('Enter a title and valid YouTube URL.', 'warning'); return } setSaving(true); try { await apiPost('/admin/live-streams', { event_config_id: form.event_config_id || null, title: form.title.trim(), youtube_url: form.youtube_url.trim(), visibility: form.visibility, status: form.status, offline_message: form.offline_message || null, scheduled_at: fromDateTimeLocal(form.scheduled_at) }); notify('Live-stream configuration saved.', 'success'); await load() } catch (err) { notify(err.message, 'error') } finally { setSaving(false) } }
  return <div className="space-y-6"><PageHeader eyebrow="Live coverage" title="YouTube live streams" description="Control the stream title, event association, visibility and current live status." actions={<Button variant="secondary" icon={RefreshCw} onClick={load}>Refresh</Button>} />
    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><h2 className="section-title">Add or update a stream</h2><p className="section-copy">Selecting an event updates the existing stream for that event when present.</p><form className="mt-5 space-y-4" onSubmit={save}><Select label="Event" value={form.event_config_id} onChange={(e) => update('event_config_id', e.target.value)}><option value="">General event stream</option>{events.map((event) => <option key={event.id} value={event.id}>{event.sport_name} · {event.category}</option>)}</Select><Input label="Stream title" value={form.title} onChange={(e) => update('title', e.target.value)} placeholder="BNMIT ODYSSEY live" /><Input label="YouTube URL" type="url" value={form.youtube_url} onChange={(e) => update('youtube_url', e.target.value)} placeholder="https://www.youtube.com/watch?v=..." /><div className="grid gap-4 sm:grid-cols-2"><Select label="Visibility" value={form.visibility} onChange={(e) => update('visibility', e.target.value)}><option value="PUBLIC">Public</option><option value="PED_ONLY">PED only</option><option value="HIDDEN">Hidden</option></Select><Select label="Status" value={form.status} onChange={(e) => update('status', e.target.value)}>{['SCHEDULED','LIVE','ENDED','OFFLINE'].map((v) => <option key={v}>{v}</option>)}</Select></div><Input label="Scheduled time" type="datetime-local" value={form.scheduled_at} onChange={(e) => update('scheduled_at', e.target.value)} /><Textarea label="Offline message" value={form.offline_message} onChange={(e) => update('offline_message', e.target.value)} placeholder="Live stream will appear here at 9:00 AM." /><Button type="submit" className="w-full" icon={Save} loading={saving}>Save stream</Button></form></Card>
      <Card className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="section-title">Public stream list</h2><p className="section-copy">Public and non-offline streams returned by the current backend endpoint.</p></div>{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : streams.length === 0 ? <EmptyState icon={Radio} title="No public streams configured" description="Add the official YouTube URL and choose Public visibility." /> : <div className="grid gap-4 p-5 md:grid-cols-2">{streams.map((stream) => <article key={stream.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-red-50 p-2 text-red-600"><Radio className="h-5 w-5" /></div><StatusBadge status={stream.status} /></div><h3 className="mt-4 font-bold text-slate-950">{stream.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{stream.offline_message || 'No offline message configured.'}</p><div className="mt-4 flex gap-2"><Button size="sm" variant="secondary" onClick={() => edit(stream)}>Edit</Button><a href={stream.youtube_url} target="_blank" rel="noreferrer" className="inline-flex min-h-9 items-center gap-2 rounded-xl bg-brand-700 px-3 py-1.5 text-xs font-bold text-white hover:bg-brand-800">Open YouTube <ExternalLink className="h-3.5 w-3.5" /></a></div></article>)}</div>}</Card></div>
  </div>
}
