import { useEffect, useState } from 'react'
import { Download, FileSpreadsheet, FileText } from 'lucide-react'
import { apiGet, downloadFile, withQuery } from '../api/client'
import { Button, Card, PageHeader, Select, Input } from '../components/ui'
import { useToast } from '../context/ToastContext'

const reportTypes = [
  ['registrations','Registration master'], ['students','Student master'], ['payments','Payment reconciliation'], ['attendance','Attendance report'], ['certificates','Certificate report'], ['fixtures','Fixture publication log'],
]

export default function ReportsPage() {
  const { notify } = useToast(); const [events, setEvents] = useState([]); const [filters, setFilters] = useState({ report: 'students', event_config_id: '', college: '', status: '', payment_status: '' }); const [busy, setBusy] = useState('')
  useEffect(() => { apiGet('/admin/events').then(setEvents).catch((err) => notify(err.message, 'error')) }, [])
  function update(key, value) { setFilters((current) => ({ ...current, [key]: value })) }
  async function download(type) { setBusy(type); try { const params = { event_config_id: filters.event_config_id, college: filters.college, status: filters.status, payment_status: filters.payment_status }; if (type === 'csv') { params.report = filters.report; await downloadFile(withQuery('/admin/reports/export.csv', params), `odyssey-${filters.report}-report.csv`) } else await downloadFile(withQuery('/admin/reports/workbook.xlsx', params), 'bnmit-odyssey-report.xlsx'); notify('Report download started.', 'success') } catch (err) { notify(err.message, 'error') } finally { setBusy('') } }
  return <div className="space-y-6"><PageHeader eyebrow="Management reporting" title="Excel and CSV exports" description="Export clean, segregated operational data by event, college, approval, payment, attendance and certificate status." />
    <Card className="p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Select label="CSV report type" value={filters.report} onChange={(e) => update('report', e.target.value)}>{reportTypes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Select label="Event and category" value={filters.event_config_id} onChange={(e) => update('event_config_id', e.target.value)}><option value="">All events</option>{events.map((event) => <option key={event.id} value={event.id}>{event.sport_name} · {event.category}</option>)}</Select><Input label="College contains" value={filters.college} onChange={(e) => update('college', e.target.value)} placeholder="BNM Institute" /><Select label="Approval status" value={filters.status} onChange={(e) => update('status', e.target.value)}><option value="">All statuses</option>{['UNDER_REVIEW','CORRECTION_REQUIRED','APPROVED','REJECTED'].map((v) => <option key={v}>{v}</option>)}</Select><Select label="Payment status" value={filters.payment_status} onChange={(e) => update('payment_status', e.target.value)}><option value="">All statuses</option>{['UNPAID','PENDING','PAID','FAILED'].map((v) => <option key={v}>{v}</option>)}</Select></div></Card>
    <div className="grid gap-5 md:grid-cols-2"><Card className="p-6"><div className="rounded-2xl bg-brand-50 p-4 text-brand-700"><FileText className="h-7 w-7" /></div><h2 className="mt-5 text-xl font-black text-brand-950">Focused CSV report</h2><p className="mt-2 text-sm leading-6 text-slate-500">Downloads the selected report type as a clean CSV, suitable for quick analysis or data transfer.</p><Button className="mt-5" icon={Download} loading={busy === 'csv'} onClick={() => download('csv')}>Download CSV</Button></Card><Card className="p-6"><div className="rounded-2xl bg-emerald-50 p-4 text-emerald-700"><FileSpreadsheet className="h-7 w-7" /></div><h2 className="mt-5 text-xl font-black text-brand-950">Management Excel workbook</h2><p className="mt-2 text-sm leading-6 text-slate-500">Creates one workbook with summary, registrations, students, payments, attendance and certificate sheets.</p><Button className="mt-5" variant="accent" icon={Download} loading={busy === 'excel'} onClick={() => download('excel')}>Download Excel workbook</Button></Card></div>
    <Card className="p-5"><h2 className="section-title">Privacy reminder</h2><p className="section-copy">Exports may contain student USNs, phone numbers and storage references. Share them only with authorised event administrators and delete local copies when no longer needed.</p></Card>
  </div>
}
