import { AlertTriangle, ChevronLeft, ChevronRight, Inbox, LoaderCircle, X } from 'lucide-react'
import { cn } from '../utils/format'

const buttonVariants={
  primary:'bg-brand-950 text-white hover:bg-brand-800 focus-visible:ring-brand-200 shadow-brand-950/10',
  secondary:'border border-brand-900/15 bg-white text-brand-800 hover:border-brand-900/25 hover:bg-cream focus-visible:ring-brand-100',
  danger:'bg-red-600 text-white hover:bg-red-700 focus-visible:ring-red-200',
  ghost:'bg-transparent text-slate-600 hover:bg-brand-50 hover:text-brand-900 focus-visible:ring-brand-100 shadow-none',
  accent:'bg-accent-500 text-white hover:bg-accent-600 focus-visible:ring-accent-200 shadow-accent-500/15',
}
const buttonSizes={sm:'min-h-9 px-3 py-1.5 text-xs',md:'min-h-10 px-4 py-2 text-sm',lg:'min-h-12 px-5 py-3 text-sm',icon:'h-10 w-10 p-0'}

export function Button({children,variant='primary',size='md',className,loading=false,icon:Icon,type='button',...props}){return <button type={type} className={cn('inline-flex items-center justify-center gap-2 rounded-xl font-bold shadow-sm transition duration-200 hover:-translate-y-0.5 focus:outline-none focus-visible:ring-4 disabled:cursor-not-allowed disabled:opacity-55 disabled:hover:translate-y-0',buttonVariants[variant],buttonSizes[size],className)} disabled={loading||props.disabled} {...props}>{loading?<LoaderCircle className="h-4 w-4 animate-spin"/>:Icon?<Icon className="h-4 w-4"/>:null}{children}</button>}
export function Card({children,className}){return <section className={cn('surface',className)}>{children}</section>}
export function Input({label,id,hint,error,className,...props}){const inputId=id||props.name;return <div className={className}>{label?<label htmlFor={inputId} className="field-label">{label}</label>:null}<input id={inputId} className={cn('field-control',error&&'border-red-400 focus:border-red-500 focus:ring-red-100')} aria-invalid={Boolean(error)} aria-describedby={hint||error?`${inputId}-help`:undefined} {...props}/>{error||hint?<p id={`${inputId}-help`} className={cn('helper-text',error&&'text-red-600')}>{error||hint}</p>:null}</div>}
export function Select({label,id,hint,error,children,className,...props}){const inputId=id||props.name;return <div className={className}>{label?<label htmlFor={inputId} className="field-label">{label}</label>:null}<select id={inputId} className={cn('field-control',error&&'border-red-400 focus:border-red-500 focus:ring-red-100')} aria-invalid={Boolean(error)} aria-describedby={hint||error?`${inputId}-help`:undefined} {...props}>{children}</select>{error||hint?<p id={`${inputId}-help`} className={cn('helper-text',error&&'text-red-600')}>{error||hint}</p>:null}</div>}
export function Textarea({label,id,hint,error,className,...props}){const inputId=id||props.name;return <div className={className}>{label?<label htmlFor={inputId} className="field-label">{label}</label>:null}<textarea id={inputId} className={cn('field-control min-h-28 resize-y',error&&'border-red-400 focus:border-red-500 focus:ring-red-100')} aria-invalid={Boolean(error)} aria-describedby={hint||error?`${inputId}-help`:undefined} {...props}/>{error||hint?<p id={`${inputId}-help`} className={cn('helper-text',error&&'text-red-600')}>{error||hint}</p>:null}</div>}

const badgeTones={neutral:'bg-slate-100 text-slate-700 ring-slate-200',blue:'bg-brand-50 text-brand-800 ring-brand-200',green:'bg-emerald-50 text-emerald-700 ring-emerald-200',amber:'bg-amber-50 text-amber-800 ring-amber-200',red:'bg-red-50 text-red-700 ring-red-200',violet:'bg-violet-50 text-violet-700 ring-violet-200'}
export function Badge({children,tone='neutral',className}){return <span className={cn('inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold ring-1 ring-inset',badgeTones[tone],className)}>{children}</span>}
export function statusTone(status=''){const value=String(status).toUpperCase();if(['APPROVED','PAID','PUBLISHED','PRESENT','RESOLVED','ACTIVE','LIVE'].includes(value))return'green';if(['UNDER_REVIEW','SCHEDULED','CREATED','DRAFT','UNKNOWN'].includes(value))return'blue';if(['CORRECTION_REQUIRED','PENDING','UNPAID','ABSENT','SUPERSEDED'].includes(value))return'amber';if(['REJECTED','FAILED','INACTIVE','OFFLINE'].includes(value))return'red';return'neutral'}

export function PageHeader({title,description,eyebrow,actions}){return <div className="relative overflow-hidden rounded-[24px] border border-brand-900/10 bg-paper px-5 py-5 shadow-soft sm:px-6 sm:py-6"><div className="absolute left-0 top-0 h-full w-1 bg-accent-500"/><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0">{eyebrow?<p className="mb-2 text-[10px] font-extrabold uppercase tracking-[.18em] text-accent-600">{eyebrow}</p>:null}<h1 className="font-display text-2xl font-black tracking-[-.04em] text-brand-950 sm:text-[32px]">{title}</h1>{description?<p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{description}</p>:null}</div>{actions?<div className="flex shrink-0 flex-wrap gap-2">{actions}</div>:null}</div></div>}
export function EmptyState({icon:Icon=Inbox,title,description,action}){return <div className="flex min-h-64 flex-col items-center justify-center px-6 py-12 text-center"><div className="mb-4 rounded-2xl bg-brand-50 p-4 text-brand-700"><Icon className="h-7 w-7"/></div><h3 className="font-display text-base font-black text-brand-950">{title}</h3>{description?<p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{description}</p>:null}{action?<div className="mt-5">{action}</div>:null}</div>}
export function LoadingState({label='Loading data'}){return <div className="surface flex min-h-56 items-center justify-center gap-3 text-sm font-semibold text-slate-500" role="status"><LoaderCircle className="h-5 w-5 animate-spin text-accent-500"/><span>{label}</span></div>}
export function ErrorState({message,onRetry}){return <div className="surface flex min-h-56 flex-col items-center justify-center px-6 text-center"><div className="mb-4 rounded-2xl bg-red-50 p-4 text-red-600"><AlertTriangle className="h-7 w-7"/></div><h3 className="font-display text-base font-black text-brand-950">We could not load this section</h3><p className="mt-2 max-w-xl text-sm leading-6 text-slate-600">{message}</p>{onRetry?<Button className="mt-5" variant="secondary" onClick={onRetry}>Try again</Button>:null}</div>}

export function Modal({open,onClose,title,description,children,footer,size='lg'}){if(!open)return null;const sizes={sm:'max-w-md',md:'max-w-xl',lg:'max-w-3xl',xl:'max-w-5xl'};return <div className="fixed inset-0 z-50 flex items-end justify-center bg-brand-950/60 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button type="button" className="absolute inset-0 cursor-default" onClick={onClose} aria-label="Close dialog backdrop"/><div className={cn('relative flex max-h-[92vh] w-full flex-col overflow-hidden rounded-t-[28px] bg-paper shadow-2xl sm:rounded-[28px]',sizes[size])}><div className="flex items-start justify-between gap-4 border-b border-brand-900/10 px-5 py-4 sm:px-6"><div><h2 id="dialog-title" className="font-display text-lg font-black text-brand-950">{title}</h2>{description?<p className="mt-1 text-sm leading-5 text-slate-500">{description}</p>:null}</div><button type="button" onClick={onClose} className="rounded-xl p-2 text-slate-500 transition hover:bg-cream hover:text-brand-950" aria-label="Close dialog"><X className="h-5 w-5"/></button></div><div className="overflow-y-auto px-5 py-5 sm:px-6">{children}</div>{footer?<div className="flex flex-wrap justify-end gap-2 border-t border-brand-900/10 bg-cream/60 px-5 py-4 sm:px-6">{footer}</div>:null}</div></div>}
export function ConfirmDialog({open,onClose,onConfirm,title,description,confirmLabel='Confirm',tone='danger',loading=false}){return <Modal open={open} onClose={onClose} title={title} description={description} size="sm" footer={<><Button variant="secondary" onClick={onClose} disabled={loading}>Cancel</Button><Button variant={tone} onClick={onConfirm} loading={loading}>{confirmLabel}</Button></>}><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">Review the information before continuing. This action may trigger emails or change participant access.</div></Modal>}
export function Pagination({page,pageSize,total,onPageChange}){const totalPages=Math.max(1,Math.ceil(total/pageSize));return <div className="flex flex-col gap-3 border-t border-brand-900/10 bg-cream/35 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs font-semibold text-slate-500">Showing {total?(page-1)*pageSize+1:0}–{Math.min(page*pageSize,total)} of {total}</p><div className="flex items-center gap-2"><Button variant="secondary" size="sm" icon={ChevronLeft} disabled={page<=1} onClick={()=>onPageChange(page-1)}>Previous</Button><span className="min-w-20 text-center text-xs font-bold text-brand-700">Page {page} of {totalPages}</span><Button variant="secondary" size="sm" disabled={page>=totalPages} onClick={()=>onPageChange(page+1)}>Next <ChevronRight className="h-4 w-4"/></Button></div></div>}
